version: '3.8'

services:
  mq:
    image: ibmcom/mq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_APP_PASSWORD=passw0rd
      - MQ_CHANNEL=DEV.APP.SVRCONN
      - MQ_TRANSPORT_TYPE=TCP
      - MQ_LISTENER_PORT=1414
      - MQ_TOPIC_PREFIX=test/
      - MQ_TOPIC=test/test1:DEV.QUEUE.1;test/test2:DEV.QUEUE.2
    volumes:
      - ./mq_data:/mnt/mqm
